# These are supported funding model platforms

github: [zickkeen]
patreon: zickkeen
liberapay: zickkeen
custom: ["https://paypal.me/donateZickkeen", "https://buymeacoff.ee/zickkeen", "https://sociabuzz.com/zickkeen/tribe"]
